import { Metadata_ } from './layout'
import {Inter} from 'next/font/google'
import './globals.css'


describe('layout', ()=> {
    it("should render the correct title and description as default in Metadata_", () => {
        const expectedMetadata = {
            title: 'Create Next App',
            description: 'Generated by create next app'
        }
        expect(Metadata_).toEqual(expectedMetadata)
    })

    it("should import Inter font with no errors", () => {
        expect(Inter).toBeDefined()
        expect(Inter).not.toBeNull()
    })

    it("should render a specific style from globals.css", () => {
        expect(true).toBe(true)
    })
})


// <html lang="en" data-theme="winter">
